In [17]:
import numpy as np
import pandas as pd

In [18]:
# Load the data
df = pd.read_csv('heart_disease.csv')
df.head()

age  cholesterol  has_heart_disease
0   68          158                  0
1   58          237                  0
2   44          278                  0
3   72          285                  0
4   37          212                  0

In [19]:
# Extract features and labels
X = df[['age', 'cholesterol']].values ## (100, 2) - 100 rows and 2 cols. to see better just run without `shape` extension
y = df['has_heart_disease'].values.reshape(100, 1) # we reshaped it form array to indeed a numpy array. Now it looks like real row-col combination. (100, 1)

# Get the number of features
n_features = X.shape[1] # Which is two in our case because we got 2 columns

# Initialize weights and biase
w = np.zeros((n_features, 1))
b = 0.0

print("Initial weight:\n", w)
print("Initial biase:\n", b)

Initial weight:
 [[0.]
 [0.]]
Initial biase:
 0.0


In [20]:
# Coding the Sigmoid function where it will takr any linear number such as (3.5, -10, 100, 6) and squich it between (0 and 1)
def sigmoid(z):
  """
  Compute the sigmoid of z
  z can be scalar or a NumPy array

  """

  return 1 / (1 + np.exp(-z)) # np.exp(-z) e^-z


print(sigmoid(0))
print(sigmoid(10))
print(sigmoid(-10))
print(sigmoid(423))
print(sigmoid(np.array([1, -10, 56, -5])))

0.5
0.9999546021312976
4.5397868702434395e-05
1.0
[7.31058579e-01 4.53978687e-05 1.00000000e+00 6.69285092e-03]


In [21]:
# Forward Propagation aka Computing Predictions
def predict_probability(X, w, b):
  """
  Compute predicted probabilities using sigmoid(w.T * X + b)
  X shape: (m, n)
  w shape: (n, 1)
  b: scalar
  Returns: (m, 1) vector of probabilities
  """

  z = np.dot(X, w) + b
  return sigmoid(z)

In [22]:
# Let's check our probabilites now
y_hat = predict_probability(X, w, b);
print(y_hat[:5])

[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]]


In [23]:
# Let's calculate loss fucntionhere to see the ifference between actual and predicted output
def compute_loss(y_hat, y):
  """
  Compute the binary cross-entropy loss
  y_hat shape: (m, 1)
  y shape: (m, 1)
  Returns: scalar loss value
  """

  m = y.shape[0]

  # Prevent log(0) by clipping
  epsilon = 1e-15
  y_hat = np.clip(y_hat, epsilon, 1 - epsilon)

  # Compute the loss
  loss = -(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))
  return np.sum(loss) / m

In [24]:
loss = compute_loss(y_hat, y)
print("Initial loss:", loss)

Initial loss: 0.6931471805599453


In [25]:
# Compute gradient
def compute_gradient(X, y, y_hat):
  """
  Compute gradient of loss w.r.t weights and bias
  Returns: dw, db
  """

  m = X.shape[0]
  dz = y_hat - y   # shape (m, 1)
  dw = (1/m) * np.dot(X.T, dz) # shape (n, 1)
  db = (1/m) * np.sum(dz)  # scalar

  return dw, db

In [26]:
dw, db = compute_gradient(X, y, y_hat)
print("dw:\n", dw)
print("db:\n", db)

dw:
 [[ 25.565]
 [107.965]]
db:
 0.48


In [27]:
# Gradient Descent
def update_parameters(w, b, dw, db, learning_rate):
  """
  Update weights and bias using gradient descent
  """

  w = w - learning_rate * dw
  b = b - learning_rate * db
  return w, b

In [28]:
learning_rate = 0.01
w, b = update_parameters(w, b, dw, db, learning_rate)

print("Updated weights:\n", w)
print("Updated biase:\n", b)

Updated weights:
 [[-0.25565]
 [-1.07965]]
Updated biase:
 -0.0048


In [29]:
# Training loop
def train(X, y, w, b, learning_rate=0.01, epochs=1000, print_every=100):
  losses = []
  for i in range(epochs):

    # Step 1: Forward pass aka execute mode and take some steps
    z = np.dot(X, w) + b
    y_hat = sigmoid(z)

    # Step 2: Compute Loss
    loss = compute_loss(y_hat, y)
    losses.append(loss)

    # Step 3: Backpropagation aka now take some steps back adn eadjust better
    dw, db = compute_gradient(X, y, y_hat)

    # Step 4: Parameter update
    w, b = update_parameters(w, b, dw, db, learning_rate)

    # Optional but good

    if i % print_every == 0 or i == epochs - 1:
      print(f"Epoch {i}: Loss = {loss:.4f}")

  return w, b, losses





In [30]:
# Train and get the result of yout training
w, b, losses = train(X, y, w, b, learning_rate=0.01, epochs=1000)

Epoch 0: Loss = 0.6908
Epoch 100: Loss = 0.2603
Epoch 200: Loss = 0.6908
Epoch 300: Loss = 0.6908
Epoch 400: Loss = 0.3347
Epoch 500: Loss = 0.6908
Epoch 600: Loss = 0.6908
Epoch 700: Loss = 0.6908
Epoch 800: Loss = 0.6908
Epoch 900: Loss = 0.6908
Epoch 999: Loss = 0.6908


In [31]:
def predict(X, w, b, threshold=0.5):
    """
    Predict 0 or 1 using trained weights and bias
    """
    probs = sigmoid(np.dot(X, w) + b)
    return (probs >= threshold).astype(int)

def accuracy(y_pred, y_true):
    """
    Compute accuracy % between predictions and actual labels
    """
    return np.mean(y_pred == y_true) * 100


In [32]:
y_pred = predict(X, w, b)
acc = accuracy(y_pred, y)

print("Predictions:\n", y_pred[:10].ravel())  # first 10
print("True labels:\n", y[:10].ravel())
print(f"Accuracy: {acc:.2f}%")


Predictions:
 [0 0 0 0 0 0 0 0 0 0]
True labels:
 [0 0 0 0 0 0 0 0 0 0]
Accuracy: 98.00%
